# Generated by Django 4.2.7 on 2025-07-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='professors/')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('research_interests', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('h_index', models.IntegerField()),
                ('famous_articles', models.TextField()),
                ('google_scholar_url', models.URLField()),
                ('researchgate_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
